### ISSUE TITLE
Could you please provide the CASP 13 test set which you evaluated on?

### ISSUE THREAD

**Issue by JudeWells** [ISYSLAB-HUST/Res-Dom#1]
I understand that the CASP 13 proteins are available from the CASP website but I wasn't sure which of the proteins that you kept for test evaluation and which boundary definitions you used as there are some discrepancies in the CASP domain annotations on their website. Thanks!

**Comment by wangleiofficial** [comment]
@JudeWells hi, the independent test dataset collected from Critical Assessments of Structure Prediction (CASP)13 is listed. 
Some details：after removing protein chains with length < 80 residues or domain length < 40 residues there were a total of 48 target sequences in CASP13 remaining.

```
T0949
T0950
T0951
T0954
T0958
T0959
T0960
T0961
T0962
T0963
T0964
T0965
T0966
T0967
T0969
T0970
T0971
T0975
T0976
T0977
T0978
T0979
T0981
T0982
T0983
T0984
T0987
T0989
T0990
T0991
T0992
T0995
T0997
T0998
T1000
T1001
T1002
T1003
T1004
T1005
T1006
T1008
T1010
T1011
T1013
T1014
T1016
T1018
```
